"""job table

Revision ID: 150fc873a6ee
Revises: 6742b5e8f034
Create Date: 2018-08-29 11:20:40.952975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150fc873a6ee'
down_revision = '6742b5e8f034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=140), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_timestamp'), 'job', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_timestamp'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
