"""job table

Revision ID: 52ac551b760e
Revises: 01486ea8a68f
Create Date: 2018-08-13 14:01:25.632540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ac551b760e'
down_revision = '01486ea8a68f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=140), nullable=True),
    sa.Column('location', sa.String(length=140), nullable=True),
    sa.Column('department', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_timestamp'), 'job', ['timestamp'], unique=False)
    op.drop_index('ix_jobs_timestamp', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.VARCHAR(length=140), nullable=True),
    sa.Column('location', sa.VARCHAR(length=140), nullable=True),
    sa.Column('department', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_timestamp', 'jobs', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_job_timestamp'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
