"""empty message

Revision ID: 5a210e04c2da
Revises: 52ac551b760e
Create Date: 2018-08-13 22:00:31.252451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a210e04c2da'
down_revision = '52ac551b760e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_timestamp', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.VARCHAR(length=140), nullable=True),
    sa.Column('location', sa.VARCHAR(length=140), nullable=True),
    sa.Column('department', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_timestamp', 'job', ['timestamp'], unique=False)
    # ### end Alembic commands ###
