"""empty message

Revision ID: 6742b5e8f034
Revises: 2afbe055340e
Create Date: 2018-08-29 11:18:25.931177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6742b5e8f034'
down_revision = '2afbe055340e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_timestamp', table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('department', sa.VARCHAR(length=200), nullable=True),
    sa.Column('link', sa.VARCHAR(length=200), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('company', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_timestamp', 'job', ['timestamp'], unique=False)
    # ### end Alembic commands ###
